Veiculo monza = new Veiculo();
monza.cor = "Azul";
monza.modelo = "2.0";
monza.capacidade = 2;
monza.rodas = 4;
monza.marca = "Fiat";
Console.WriteLine(monza.modelo);
Console.WriteLine(monza.capacidade);
Console.WriteLine(monza.rodas);
Console.WriteLine(monza.marca);
Console.WriteLine(monza.cor);